Completed support for -printer in nxclient together with handling of drivers cache.
The component now works exactly like the commercial nxclient.

diff --git a/freenx/nxclient b/freenx/nxclient
--- a/freenx/nxclient
+++ b/freenx/nxclient
@@ -9,7 +9,7 @@
 #       but we set it to a "good value" anyway in case 
 #       it does check it someday.
 #
-# CVS: $Id: nxclient,v 1.4 2005/03/24 01:33:19 fabianx Exp $
+# CVS: $Id: nxclient,v 1.5 2005/04/25 02:11:24 fabianx Exp $
 #
 # ========================================================================
 
@@ -73,6 +73,9 @@ fi
 #	set <name> <driver> <description> - sets the current driver and description for name
 #	getvendlist - gets a list of vendors
 #	getdrvlist <vendor> - gets a list of drivers for vendor
+#	getextdrvlist <vendor> - gets an extended list (with driver and 
+#                                description) of drivers for vendor
+#	getdesc <driver> - gets the description for driver <driver>
 #	getlist - gets a list of drivers
 
 #
@@ -104,10 +107,17 @@ utility_printer()
 			mv -f $UTILITY_DRIVERS_CACHE.tmp $UTILITY_DRIVERS_CACHE
 		;;
 		getvendlist)
-			$UTILITY_NXPRINT -d | awk -F'|' '{ print $2 }' | uniq
+			$UTILITY_NXPRINT -d | awk -F'|' '{ print $2 }' | uniq | tr '\n' '|'
 		;;
 		getdrvlist)
-			$UTILITY_NXPRINT -d | awk -F'|' '($2=="'$2'") { print $4 }'
+			$UTILITY_NXPRINT -d | awk -F'|' '($2=="'$2'") { print $4}' | tr '\n' '|'
+		;;
+		getextdrvlist)
+			$UTILITY_NXPRINT -d | awk -F'|' '($2=="'$2'") { print $4 "|" $3 }'
+		;;
+
+		getdesc)
+			$UTILITY_NXPRINT -d | awk -F'|' '($4=="'$2'") { print $3}'
 		;;
 		getlist)
 			$UTILITY_NXPRINT -d
@@ -148,12 +158,38 @@ xmessage_quit()
 
 xmessage_printer_ask()
 {
-	$xmessage -buttons "Ok:0,Configure:1,Cancel:2" -center "$DIALOG_MESSAGE"
+	$xmessage -buttons "Ok:100,Configure:101,Cancel:102" -center "$DIALOG_MESSAGE"
+	RC=$?
+	[ $RC -lt 100 ] && return 2
+	let RC=$RC-100
+	return $RC
 }
 
-xmessage_printer()
+xmessage_printer_configure()
 {
-	:
+	IFS=','
+	$xmessage -buttons "$*" -center "$DIALOG_MESSAGE"
+	RC=$?
+	unset IFS
+	VENDOR=""
+	if [ $RC -gt 100 ]
+	then
+		let NR=$RC-100
+		VENDOR="${!NR}"
+	fi
+	echo "$VENDOR"
+}
+
+xmessage_printer_configure_vendor()
+{
+	IFS='|' VENDOR_LIST=( $(utility_printer getvendlist) )
+	xmessage_printer_configure "${VENDOR_LIST[@]}"
+}
+
+xmessage_printer_configure_driver()
+{
+	IFS='|' DRIVER_LIST=( $(utility_printer getdrvlist "$1") )
+	xmessage_printer_configure "${DRIVER_LIST[@]}"
 }
 
 #
@@ -198,16 +234,25 @@ xdialog_quit()
 
 xdialog_printer_ask()
 {
-		$DIALOG --title "$DIALOG_CAPTION" --buttons-style text --ok-label "Ok" --cancel-label "Configure" --yesno "$DIALOG_MESSAGE\n\nClose window to cancel." 400x250
+	$DIALOG --title "$DIALOG_CAPTION" --buttons-style text --ok-label "Ok" --cancel-label "Configure" --yesno "$DIALOG_MESSAGE\n\nClose window to cancel." 400x250
 	RC=$?
 	[ $RC -eq 255 ] && return 2
 	return $RC
 }
 
-xdialog_printer()
+xdialog_printer_configure_vendor()
 {
-	:
+	IFS='|' VENDOR_LIST=( $(utility_printer getvendlist | sed 's/|/||off|/g') )
+	$DIALOG --stdout --title "$DIALOG_CAPTION" --radiolist "$DIALOG_MESSAGE" 0 0 6 "${VENDOR_LIST[@]}"
 }
+
+# xdialog_printer_configure_driver vendor old_driver
+xdialog_printer_configure_driver()
+{
+	IFS='|' XDIALOG_LIST=( $(utility_printer getextdrvlist "$1" | sed 's/$/|off/g; /'"$2"'/ s/|off/|on/g' | tr '\n' '|') )
+	$DIALOG --stdout --title "$DIALOG_CAPTION" --radiolist "$DIALOG_MESSAGE" 0 0 6 "${XDIALOG_LIST[@]}"
+}
+
 
 #
 # helper functions
@@ -225,17 +270,31 @@ helper_dialog_printer()
 		DIALOG_MESSAGE=$(echo -e "Found driver for printer $DIALOG_PRINTER.\n\nOld choice was: ${PRINTER_INFORMATION[3]}.\n\nIf you want to keep the settings click on 'Ok' \n- else click on 'Configure'.") ${dialog_interface}_printer_ask
 		RC=$?
 		# bail out with exit code 2 in case the user cancelled the operation
-		[ $RC -eq 2 ] && exit 2
+		[ $RC -eq 2 ] && echo "cancel: aborted" && exit 2
 		[ $RC -eq 0 ] && PRINTER_CONFIGURE="no"
 	fi
+	
+	VENDOR=""
+	OLD_DRIVER="${PRINTER_INFORMATION[2]}"
 
 	if [ "$PRINTER_CONFIGURE" = "yes" ]
 	then
-		DIALOG_MESSAGE="Not implemented." ${dialog_interface}_ok
+		DRIVER=""
+		VENDOR=$(DIALOG_MESSAGE="Choose vendor for printer $DIALOG_PRINTER." ${dialog_interface}_printer_configure_vendor)
+		[ -n "$VENDOR" ] && DRIVER=$(DIALOG_MESSAGE="Choose driver for printer $DIALOG_PRINTER." ${dialog_interface}_printer_configure_driver "$VENDOR" "${OLD_DRIVER:-invalid}")
+		# set the new printer driver
+		if [ -n "$DRIVER" ]
+		then
+			DESC=$(utility_printer getdesc "$DRIVER")
+			utility_printer set "$DIALOG_PRINTER" "$DRIVER" "$DESC"
+		fi
+	else
+		DRIVER="$OLD_DRIVER"
 	fi
 
 	# echo the choosen <ppdfile> to stdout
-	echo "${PRINTER_INFORMATION[2]}"
+	[ -n "$DRIVER" ] && echo "$DRIVER"
+	[ -z "$DRIVER" ] && echo "cancel: aborted" && exit 2
 			
 	exit 0
 }
